apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: voting-app
  namespace: argocd
spec:
  source:
    path: app-k8s-resources/app
    repoURL: https://github.com/ivanactum/app-development-kubernetes.git
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev
  project: default