apiVersion: v1
kind: Service
metadata:
  labels:
    app: vote
  name: svc-vote
spec:
  # type: NodePort
  ports:
  - name: "vote-service"
    port: 80
    targetPort: 80
  - name: "vote-metrics"
    port: 5050
    targetPort: 5050
  selector:
    app: vote
  
