apiVersion: v1
kind: Service
metadata:
  name: vote-lb
  labels:
    app: vote
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    name: app
  - port: 5050
    targetPort: 5050
    name: metrics
  selector:
    app: vote