name: IaC - Create AKS Cluster - Azure

on:
  workflow_dispatch:
     
jobs:
  create-aks-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      # - name: 'Az CLI login'
      #   uses: azure/login@v1
      #   with:
      #     creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: 'Az CLI login'
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      - name: 'Run az aks create'
        shell: pwsh
        run: |
            $akslist=$(az aks list -g ivan-test)
            if (!$akslist.Equals("[]")) {
              echo "cluster exists!"
            } else {
              az aks create --resource-group ivan-test --name myAKSCluster --node-count 2 --generate-ssh-keys
            }
            
      - name: Set AKS context
        id: set-context
        uses: azure/aks-set-context@v3
        with:
          resource-group: 'ivan-test' 
          cluster-name: 'myAKSCluster'

      - name: Setup kubectl
        id: install-kubectl
        uses: azure/setup-kubectl@v3


      # - name: 'kubectl apply'
      #   shell: pwsh
      #   working-directory: ./app-k8s-resources/app/
      #   run: |
      #       kubectl apply -f ./
      
      - name: 'Install ArgoCD'
        shell: pwsh
        run: |
            kubectl create namespace argocd
            kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

      - name: 'Adding apps to argoCD'
        shell: pwsh
        working-directory: ./app-k8s-resources/argocd/
        run: |
            kubectl create namespace dev
            kubectl apply -n argocd -f ./application.yaml